### ISSUE TITLE
Visual Bugs

### ISSUE THREAD

**Issue by Fredi100** [Calvein/acnh-surf-n-turf#1]
While using your awesome tool for tracking the fish I caught I found some minor visual bugs.
1. The Input field and drop down menus are not currently readable.
![snip1](https://user-images.githubusercontent.com/2962747/77275098-ba61ad80-6cb7-11ea-84e6-3aa9248f60b7.PNG)
Dropdown:
![snip2](https://user-images.githubusercontent.com/2962747/77275105-c188bb80-6cb7-11ea-837f-fe37c19b6651.PNG)

2. When marking a fish or an insect as caught and then refreshing the site, the marker will stay but the insect or fish is no longer grayed out.
![snip3](https://user-images.githubusercontent.com/2962747/77275111-c6e60600-6cb7-11ea-8634-95ee32b905e1.PNG)
Unmarking and then remarking it does not fix the problem

**Comment by Calvein** [comment]
Thanks for your feedback, I indeed have an issue with the theme but only in production 🤦‍♂
I'll try to fix it by today 👍

**Comment by Calvein** [comment]
Should be all good now 👍
